services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "je?Z_TS{'J:hYLJD"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sqlserverdata:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  sqlserverdata: